spring:
  application:
    name: cloudticket-server

server:
  port: 8080

mybatis-plus:
  configuration:
    map-underscore-to-camel-case: true
    log-impl: org.apache.ibatis.logging.slf4j.Slf4jImpl   # 开发期打印 SQL，压测前关闭
  global-config:
    banner: false

knife4j:
  enable: true
